[Material]
Default X=20.0000
Default Z=100.0000
Maximum X=100.0000
Maximum Z=50.0000
Position X=0.0000
Position Z=0.0000

[Home]
X=0.0000
Z=0.0000
Feed=500.0000
Negative X=TRUE
Negative Z=TRUE
Negative 3=FALSE
Negative 4=FALSE

[Feed]
Default=100.0000
Maximum Rate X=600.0000
Maximum Rate Z=600.0000
Maximum Rate 3=500.0000
Minimum Rate=0.0010
Steps per mill X=314.9600
Steps per mill Z=314.9600
Steps per mill F=314.9600
Motor Direction X=1
Motor Direction Z=1
Max Contour Feed=500.0000
Max Contour Angle=75.0000
Jog Rapid Feed=600
Shortest Move=0.0000
Shortest Time=0.0000
Maximum Rate 4=0.0000
Thread Accel Factor=15.0000
Upper Contour Angle=0.0000
Contour Creep Mul=0.0000

[Spindle]
Maximum Speed=2800
Minimum Speed=100
Manual=FALSE
Encoder Count=4000
Encoder Fitted=FALSE

[Machine Capability]
Maximum Cut Depth=5.0000
Travel X+=0.0000
Travel Z+=0.0000
Travel X-=-50.0000
Travel Z-=-126.0000
Cutter Compensation=FALSE
High Speed Machining=FALSE
Table Size X=50.0000
Table Size Z=50.0000
Under Inspection=FALSE
Feed Pot=TRUE
Speed Pot=TRUE
Radius Programming=FALSE
Front Turret=FALSE

[Tool Change]
Auto Changer=0
Maximum number=8
Turret number=8
Change Pos X=0.0000
Change Pos Z=0.0000

[Communications]
Control Type=9
Baud rate=57600
Com Port=1
Mint File=C:\Program Files\Denford\VRTurning\MicroTurnNS.mnt
Polling Delay=50
M Code TimeOut=10000
T Code TimeOut=60000
Stop Bits=2
Hardware Handshaking=FALSE


[Post Process]
Library=C:\Program Files\Denford\Milling\LIBS\FANUCM.SLB

;first  item=In or Out or Wait
;second item=Port Number
;third  item=Is the IO + or -
;fourth item=Timeout time in seconds
;fifth  item=Message to show
;sixth  item=ErrorMessage 
File Extension=Undefined
Denford Directives=FALSE
Add Comments=FALSE
Add Percents=FALSE
Force Points=FALSE

[MCode Description]
M3=Spindle Forward
M5=Spindle Stop
M38=Door Open
M39=Door Close
M62=Output 1 On
M63=Output 2 On
M64=Output 1 Off
M65=Output 2 Off
M66=Wait for Input 1 Activate
M67=Wait for Input 2 Activate
M76=Wait for Input 1 DeActivate
M77=Wait for Input 2 DeActivate

[MCode TimeOut]
M3=10000
M5=10000
M38=10000
M39=10000
M62=0
M63=0
M64=0
M65=0
M66=0
M67=0
M76=0
M77=0

[MCode Enabled]
M3=TRUE
M5=TRUE
M38=FALSE
M39=FALSE
M62=FALSE
M63=FALSE
M64=FALSE
M65=FALSE
M66=FALSE
M67=FALSE
M76=FALSE
M77=FALSE


[Input/Output Devices]
Tutor File=C:\PROGRAM FILES\DENFORD\VRTURNING\VRTurningTutor.keys
Com Port=0
Virtual World=C:\Program Files\Denford\VRTurning\MicroTurnNS.xvr
CIM RS232 Input=FALSE
CIM DDE Input=FALSE
Jog X plus key=VK40
Jog X minus key=VK38
Jog Z plus key=VK39
Jog Z minus key=VK37
Feed up key=VK116
Feed down key=VK117
Speed up key=VK118
Speed down key=VK119
Denford Net Enabled=FALSE
CIM Chuck Input=FALSE

[Miscellaneous]
Background Bitmap=default
Background Enabled=TRUE
Background Tiled=TRUE

