[MAIN]
No Close=1

[IO PORT DATA]
Interface Module Port=PORT2A
Clamp Bit=1
Machining Cycle Bit=0
Machine Idle=0
Clamp Open=1

[SERVICE]
Machine Name=Lathe

[FILES]
Status History=lathe.log
Commands File=lathe.cmd

[FILE EXTENSIONS]
CNC Files=fnc

[COMMS]
Port=COM3
Settings=9600,e,7,1
Flags=H2
OutBufferSize=1024
InBufferSize=1024
TimeOut=20000
ReportDownLoad=1
Flag=H2
Send Type=4
; 1=Old Fanuc 2=PNC3 3=Denford 4=Fanuc


[INTERLOCKS]
Part Clamp=2
Machine Access=1

[SAFETY BIT]
BIT=6
enable=0

[MAIN WINDOW]
X=90
Y=35
W=318
H=275
