[MAIN]
No Close=1

[IO PORT DATA]
Interface Module Port=PORT1

[SERVICE]
Machine Name=Robot1

[FILES]
Status History=robotR.log
Commands File=RobotR.cmd
Startup Download File=

[TIMER]
Sampling Interval=1000

[INTERLOCKS]
Gripper=7
Control=8

[SAFETY BIT] 
bit=6
enable=1
manual=1

[COMMS]
Port=COM1
Settings=4800,e,7,1
H3=Hardware handshaking.
; THIS MUST BE SET TO H3 and only the new DMTRS232.DLL implements this 
; handshaking. The new DMTRS232.DLL is backwards compatible with 
; the old version
Flags=H3
OutBufferSize=1024
InBufferSize=1024
; The maximum time in milliseconds that a file has to complete a download
; Set this to the maximum time that a file of DNC code will take
; to finish executing
TimeOut=180000
ReportDownLoad=1
; Emulation Mode=1 IMPLIES the Robot driver emulates an RS232 download. 
;                    It continously reads a line from the file and discards it
;                    pausing two seconds between each line read.
; Emulation Mode=0 IMPLIES the Robot driver downloads files via the RS232 port
Emulation Mode=0

// A list of messages to display at start up
[Initial Checks]
1=Make sure the E Stop is enabled ?
2=Is the robot switched on ?
3=Is there an RS232 cable between the robot and the Cell PC ?
4=About to nest the robot and move to home, is it in a safe position ?
5=Commence robot initialisation ?

[COMMAND TIMINGS]
1=10
2=8
3=10
4=8

[MAIN WINDOW]
X=232
Y=267
W=318
H=280
