; Revision History
; 18/04/00 - JHB - Changed the direction of the X axis (now homes -ve)
;                  Defaults is now Manual ToolChanger (was Auto)
; 27/4/00  - JHB - Put in shortest move (1 to 1.5 mm) to allow axes to decel in time
; 4/5/00   - AT  - Put basic (Auto Tool Change) section in for VR world Tool changes
; 11/05/00 - JHB - 'Post Process' section moved to the top of the file
;	   - AT  - Max no of tools is 8 to keep in line with VR world
; 12/5/00  - AT  - Real Machine Available=TRUE added to machine capability
; 14/06/00 - JHB - Table Size changed to 360 x 162 x 35
; 25/7/00  - AT  - Polling delay increased to 50 for version 2.5.2 comms
; 05/01/01 - JHB - Default is now Manual ToolChanger (was Auto AGAIN !!!)

[Post Process]
Library=C:\DENFORD\LIBS\FANUCM.SLB

[Material]
Default X=100
Default Y=100
Default Z=20
Maximum X=225
Maximum Y=150
Maximum Z=115
Position X=0
Position Y=0
Position Z=0

[Home]
X=0
Y=0
Z=0
Feed=500
Home Style X=0
Home Style Y=2
Home Style Z=2
Home Style IV=2
Home Time Out=55000

[Feed]
Default=100
Maximum Rate X=1000
Maximum Rate Y=1000
Maximum Rate Z=666
Maximum Rate IV=500
Minimum Rate=20
Steps per mill X=200
Steps per mill Y=200
Steps per mill Z=200
Steps per mill IV=200
Steps per mill F=200
Motor Direction X=1
Motor Direction Y=1
Motor Direction Z=1
Motor Direction IV=1
Backlash X=0
Backlash Y=0
Backlash Z=0
Backlash IV=0
Max Contour Feed=1000
Max Contour Angle=30
Upper Contour Angle=90
Contour Creep Mul=0.1
Jog Rapid Feed=600
Shortest Contour=0
Shortest Time=0

[Spindle]
Maximum Speed=5000
Minimum Speed=150
Manual=FALSE


[Machine Capability]
Maximum Cut Depth=12
Travel X+=225
Travel Y+=0
Travel Z+=0
Travel IV+=9999
Travel X-=0
Travel Y-=-150
Travel Z-=-115
Travel IV-=-9999
Cutter Compensation=TRUE
High Speed Machining=TRUE
Table Size X=360
Table Size Y=132
Table Size Z=35
Under Inspection=FALSE
Feed Pot=TRUE
Speed Pot=TRUE
External Speed Pot=FALSE
Real Machine Available=TRUE
Expand Arcs=FALSE
Min Chord Length=1
IV axis - A,B,C (1,2 or 3)=0
IV Home Switch=FALSE

[Tool Change]
Auto Changer=TRUE
Maximum number=6
X=225
Y=0
Z=0

[Auto Tool Change]
1=M24
2=T
3=M25


[Communications]
Baud rate=57600
Com Port=4
Stop Bits=1
Mint File=NOVAMILL.mnt
Polling Delay=20
T Code TimeOut=75000
Hardware Handshaking=FALSE
Control Type=9
Node=2

[Input/Output Devices]
Tutor File=VRmillingTutor.keys
Com Port=5
Denford VR DLL=NovaMill.dll
CIM RS232 Input=TRUE
Remote control cycle=TRUE
Remote control vice=TRUE
CIM Baud Rate=7
CIM RS232 Com Port=2
Editor Lines=11
Editor Colour Scheme=1

;first  item=In or Out or Wait
;second item=Port Number
;third  item=Is the IO + or -
;fourth item=Timeout time in seconds
;fifth  item=Message to show
;sixth  item=ErrorMessage 

[M3]
Description=Spindle Forward
Timeout=10000
Code=3
Enabled=TRUE

[M4]
Description=Spindle Reverse
Timeout=10000
Code=4
Enabled=FALSE

[M5]
Description=Spindle Stop
Timeout=10000
Code=5
Enabled=TRUE

[M8]
Description=Coolant On
Timeout=10000
Code=8
Enabled=FALSE

[M9]
Description=Coolant Off
Timeout=10000
Code=9
Enabled=FALSE

[M13]
Description=Coolant on and Spindle Fwd
Timeout=10000
Code=13
Enabled=FALSE

[M10]
Description=Vice Open
Timeout=10000
Code=10
Enabled=TRUE

[M11]
Description=Vice Close
Timeout=10000
Code=11
Enabled=TRUE

[M20]
Description=ATC Arm In
Timeout=10000
Code=20
Enabled=TRUE

[M21]
Description=ATC Arm Out
Timeout=10000
Code=21
Enabled=TRUE

[M24]
Description=Drawbar Unclamp
Timeout=10000
Code=24
Enabled=TRUE

[M25]
Description=Drawbar Clamp
Timeout=10000
Code=25
Enabled=TRUE

[M27]
Description=Reteach Carousel Pocket 1
Timeout=10000
Code=27
Enabled=TRUE

[M32]
Description=Rotate Carousel CW
Timeout=10000
Code=32
Enabled=TRUE

[M33]
Description=Rotate Carousel CCW
Timeout=10000
Code=33
Enabled=TRUE

[M34]
Description=Rotate Carousel Half Turn
Timeout=10000
Code=34
Enabled=TRUE

[M38]
Description=Door Open
Timeout=10000
Code=38
Enabled=TRUE

[M39]
Description=Door Close
Timeout=10000
Code=39
Enabled=TRUE

[M62]
Description=Aux output 1 ON
Timeout=0
Code=62
Enabled=TRUE

[M64]
Description=Aux output 1 OFF
Timeout=0
Code=64
Enabled=TRUE

[M63]
Description=Aux output 2 ON
Timeout=0
Code=63
Enabled=TRUE

[M65]
Description=Aux output 2 OFF
Timeout=0
Code=65
Enabled=TRUE

[M66]
Description=Wait Aux input 1 ON
Timeout=0
Code=66
Enabled=TRUE

[M76]
Description=Wait Aux input 1 OFF
Timeout=0
Code=76
Enabled=TRUE

[M67]
Description=Wait Aux input 2 ON
Timeout=0
Code=67
Enabled=TRUE

[M77]
Description=Wait Aux input 2 OFF
Timeout=0
Code=77
Enabled=TRUE
