

[73]
Rapid XYZ = 1
Rapid R = 1
;Fanuc reference (page 137)parameter 5114 d retract distance for high speed peck(mm)
Rapid Peck Z = 4
Rapid R = 1

[74]
Rapid XYZ = 1
Rapid R = 1
Spindle CCW = 1
Cut Z = 1
Spindle CW=1
Dwell = 0
Cut R = 1

[76]
Rapid XYZ = 1
Rapid R = 1
Cut Z = 1
Dwell = 0
Spindle Orientate+=1
Rapid R = 1

[81]
Rapid XYZ = 1
Rapid R = 1
Cut Z = 1
Rapid R = 1

[82]
Rapid XYZ = 1
Rapid R = 1
Cut Z = 1
Dwell = 0
Rapid R = 1

[83]
Rapid XYZ = 1
Rapid R = 1
;Fanuc reference (page 137)parameter 5114 d retract distance for high speed peck(mm)
Peck Z = 4
Rapid R = 1


[84]
Rapid XYZ = 1
Rapid R = 1
Spindle CW = 1
Cut Z = 1
Spindle CCW=1
Dwell = 0
Cut R = 1

[85]
Rapid XYZ = 1
Rapid R = 1
Cut Z = 1
Cut R = 1

[86]
Rapid XYZ = 1
Rapid R = 1
Cut Z = 1
Rapid R = 1

[87]
Rapid XYZ = 1
Spindle Orientate+=1
Rapid R = 1
Spindle Orientate-=1
Spindle CW = 1
Cut Z = 1
Spindle Orientate+=1
Rapid XYZ = 1

[89]
Rapid XYZ = 1
Rapid R = 1
Cut Z = 1
Dwell = 0
Cut R = 1

