[directories]
machine list file=C:\Program Files\Denford\VRTurning\machine list.ini
XNC Folder=C:\Program Files\Denford\VRTurning\Data\
Last Tooling=C:\Program Files\Denford\VRTurning\Tooling Files\
FNL Folder=C:\Program Files\Denford\VRTurning\CNC Files\
GNC Folder=C:\Program Files\Denford\VRTurning\Data\


[Default Settings]
Active Machine=MeteorNS
Metric=1
Help File=Turn.hlp
Help Reference=Help.ini
Billet X=25.4
Billet Z=70
Billet X Pos=0
Billet Z Pos=0
Expanded Cycles=1
Warn ON Play=0
Cutter Comp=0
PrimaryLanguage=1
SubLanguage=0
ScreenUpDate=200
Last Input=2
MintDebug=False
Support IP=62.49.128.243

[source]
File=1
Editor=2
Compiled=3
Fanuc21i=4
FanucOT=6

[Tooling]
Tool File name=C:\Program Files\Denford\VRTurning\Tooling Files\Default.tft
last tool=1
Show All Offsets=0

[RS232]
com port=0
Baud Rate=6
Data Bits=2
Parity=2
Hand Shaking=3
Stop Bits=0

[Jog Keys]
X+=37
X-=39
Y+=40
Y-=38
Z+=33
Z-=34
Trv=101

[readOut]
Font size=8
Font name=MS Sans Serif
Font Style=0

[MainForm]
Top=-4
Left=-4
Width=1032
Height=748

[EditorForm]
Top=24
Left=30
Width=300
Height=464

[screen]
Top=20
Left=39
Show Buttons=1
Left Side=0

[EditForm]
padding=SPACE
LineEnd=;
NumberString=N
numberstart=10
numberInc=10
NumberSize=3
formatting=0
Font size=8
Font name=MS Sans Serif
background colour=16777215
Token G Colour=32896
Token G BackColour=16777215
Token G Style=1
Token M Colour=0
Token M BackColour=16777215
Token M Style=0
Token T Colour=0
Token T BackColour=16777215
Token T Style=0
Token F Colour=0
Token F BackColour=16777215
Token F Style=0
Token S Colour=0
Token S BackColour=16777215
Token S Style=0
Token X Colour=0
Token X BackColour=65408
Token X Style=0
Token Y Colour=0
Token Y BackColour=16777215
Token Y Style=0
Token Z Colour=0
Token Z BackColour=16776960
Token Z Style=0
Token I Colour=0
Token I BackColour=65535
Token I Style=0
Token J Colour=0
Token J BackColour=8421631
Token J Style=0
Token ( Colour=0
Token ( BackColour=16777215
Token ( Style=0
Token [ Colour=0
Token [ BackColour=16777215
Token [ Style=0
Font Style=0
Token K Colour=0
Token K BackColour=16777215
Token K Style=0
FormatFile=C:\Program Files\Denford\VRTurning\VRTurn.ini

[Menu Tools]

[Button Map]
;FanucBut_O
0=$4F,$50
;FanucBut_N
1=$4E,$51
;FanucBut_G
2=$47,$52
;FanucBut_7
3=$37,$41
;FanucBut_8
4=$38,$42
;FanucBut_9
5=$39,$44
;FanucBut_X
6=$58,$43
;FanucBut_Z
7=90,89
;FanucBut_F
8=70,76
;FanucBut_4
9=$34,91
;FanucBut_5
10=$35,93
;FanucBut_6
11=$36,$20
;FanucBut_M
12=$4D,73
;FanucBut_S
13=$53,75
;FanucBut_T
14=$54,74
;FanucBut_1
15=$31,44
;FanucBut_2
16=50,35
;FanucBut_3
17=$33,61
;FanucBut_U
18=85,72
;FanucBut_W
19=87,86
;FanucBut_EOB
20=186,69
;FanucBut_-
21=189,43
;FanucBut_0
22=48,42
;FanucBut_.
23=190,47
;FanucBut_POS
24=24,24
;FanucBut_PROG
25=25,25
;FanucBut_OFFSET
26=26,26
;FanucBut_SHIFT
27=$10,$10
;FanucBut_Can
28=$08,$08
;FanucBut_INPUT
29=29,29
;FanucBut_GRAPH
32=232,232
;FanucBut_ALTER
33=233,233
;FanucBut_INSERT 
34=234,234
;FanucBut_DELETE
35=235,$235
;FanucButPageUp
36=$21,$21
;FanucButPageDown
37=$22,$22
;FanucButCursorLeft
38=$25,$25
;FanucButCursorRight
39=$27,$27
;FanucButCursorUp
40=$26,$26
;FanucButCursorDown
41=$28,$28
;FanucButHelp
42=42,42
;FanucButReset
43=43,43

[Turn2DForm]
Top=18
Left=322
Width=647
Height=477

[Control Panel]
Docked=0
LeftSide=0
Display=2

[CaracelAndOffsets]
Top=41
Left=31
Width=338
Height=494

[ToolLib]
Top=182
Left=36

[WorkOffsetForm]
Top=359
Left=27

[VRT_form_turn]
Top=7
Left=218
Width=272
Height=261

[Compiled Input]
Top=52
Left=33

[Draw2D]
Top=254
Left=324
Width=375
Height=199

[Editor1]
Top=6
Left=6
Width=194
Height=338

[FileInputForm]
Top=76
Left=72

[Toolbar_File_Control]
Rev=2
Visible=1
DockedTo=DockBottom
DockRow=0
DockPos=445
FloatLeft=0
FloatTop=0
IconSize=0
ShowCaption=0
FloatRightX=0

[Toolbar_machine]
Rev=2
Visible=1
DockedTo=DockRight
DockRow=0
DockPos=379
FloatLeft=0
FloatTop=0
IconSize=0
ShowCaption=1
FloatRightX=0

[Toolbar_output]
Rev=2
Visible=1
DockedTo=DockRight
DockRow=0
DockPos=28
FloatLeft=0
FloatTop=0
IconSize=0
ShowCaption=1
FloatRightX=0

[toolbar_modal]
Rev=2
Visible=1
DockedTo=DockBottom
DockRow=0
DockPos=0
FloatLeft=0
FloatTop=0
IconSize=0
ShowCaption=1
FloatRightX=0

[dataInfo]
Rev=2
Visible=0
DockedTo=DockTop
DockRow=0
DockPos=0
FloatLeft=0
FloatTop=0
IconSize=0
ShowCaption=0
FloatRightX=0

[ControlPanel]
Top=36
Left=504

[VRT_form_turn_1]
Top=44
Left=44
Width=835
Height=402

[Draw3D]
Top=54
Left=141
Width=269
Height=250

[3DGraphics]
Auto Save Bmp=1
Billet Material=6
rapid colour=255
linear colour=65280
circular colour=4227327
thread colour=65535
plastic colour=16711680
background colour=8421440
move history amount=50
use plastic=1
show linears=1
show Rapids=1
show Arcs=1
show Threads=1
show cutter=1
use Offsets=0
show move history=1
bitmap width=320
bitmap height=240

[Graphics]
Auto Save Bmp=1
rapid colour=255
linear colour=65280
circular colour=33023
thread colour=65535
material colour=16711680
centre colour=0
background colour=8421376
hi lite colour=16777215
use tool colour=0
show linears=1
show Rapids=1
show Arcs=1
show Threads=1
show cutter=1
Shaded Material=1
Show Section=1
Use Offsets=0

[Toolbar_ProgControl]
Rev=2
Visible=1
DockedTo=DockBottom
DockRow=0
DockPos=301
FloatLeft=600
FloatTop=318
IconSize=0
ShowCaption=1
FloatRightX=0


[ToolButtons Hidden]
0_11=Modal11
0_12=Modal12
0_13=Modal13
0_14=Modal14
0_15=Modal15
0_16=Modal16
0_17=Modal17
0_18=Modal18
0_19=Modal19
0_20=Modal20
0_21=Modal21
0_22=Modal22
0_23=Modal23
0_24=Modal24
0_25=Modal25

[Flash]
Flash_User=Bauman Moscow State Technical University 2-ya Baumanskaya st, 5 107005 Moscow Russian Federation 1 User Licence
Flash_Code=6DFP-1VPJ-H6EG-SRM2-GHKB-JTCV-CRPG-J85T-5WC
[Main ToolBars]
ImageSize1=1
CaptionV1=1
ImageSize2=1
CaptionV2=1
ImageSize3=1
CaptionV3=1
ImageSize4=0
CaptionV4=0
