[MAIN]
No Close=1

[IO PORT DATA]		-	-
Interface Module Port=PORT2A

[SERVICE]		-	-
Machine Name=ASRS
[FILES]			-	-
Status History=asrs.log
Commands File=asrs.cmd

[COMMS]
Port=COM4
Settings=4800,e,7,1
Flags=H2
OutBufferSize=128
InBufferSize=128

[TIMER]			-	-
Sampling Interval=500

[SAFETY BIT]
BIT=6
enable=0

[ASRS]
Rows=5
Columns=5
Sides=2
InventoryFile=invent.dat
; position numbers for the ASRS command statement: i.e. FROM 1 TO 2 -> FROM Codetag TO Conveyor
ASRS=0
Conveyor=1
AGV=2
Inconveyor=3
Codetag=4
; command examples....
;	from king to codetag
;	from king to AGV
;	from AGV to king
;	from codetag to conveyor
;	from conveyor to AGV
;
;	generic: from start to dest
;	
;		start is either a place or a part
;		dest is either a place or a part
;		if start is a part, then dest cannot be a part
;

[MAIN WINDOW]
X=222
Y=192
W=468
H=198
