[setup]
; tool type and whether or not to add tools to the toolbar
inventory=1
station=1
tool=1
robot=1
inspection=1
transport=1
misc=1
palletised segments=0

[inventory]
;highest number is default inventory device
Hopper=hopper.wmf,40,10,1
ASRS=asrs.wmf,224,173,2
;ASRS=asrs1.wmf,400,77,2

[station]
Station=station.wmf,20,20,3

[tool]
Lathe=lathe.wmf,130,61,7
Miller=miller.wmf,131,83,8
Lathe2=cyclone.wmf,201,115,27
Miller2=triac.wmf,178,94,28

[robot]
Robot=robot.wmf,54,70,11
Slide=slide.wmf,180,82,12
Robot2=rvm1.wmf,100,100,31
Slide2=rvmslide.wmf,155,100,32

[inspection]
CMM=cmm.wmf,80,82,14
VisionSystem=vision.wmf,15,30,15
CodeTag=codetag.wmf,25, 25, 19

[transport]
Conveyor=16
AGV=17

[misc]
Delay=delay.wmf,30,37,18

[palletised segments]
PalletStation=palstat.wmf,20,20,6
tlp=topleft.wmf,20,20,50
trp=topright.wmf,20,20,51
blp=botmleft.wmf,20,20,52
brp=botmrigt.wmf,20,20,53
lp=left.wmf,20,80,54
rp=right.wmf,20,80,55
tp=top.wmf,80,20,56
bp=bottom.wmf,80,20,57


[rules]
Envelopes=2 11 12 31 32
; which machines have envelopes
Station=2 11 12 15 16 17 18 19 31 32
;Station loads: ASRS, Robot, Slide, VisionSystem, AGV, Conveyor, Delay
SecondaryTransport=1 3 5 6 7 8 14 15 19 27 28
;Robot Loads: Hopper, Station, IndexStation, PalletStation, Lathe, Miller, CMM, VisionSystem, CodeTag

[envelope]
Station=-10, -10, 30, 30, 0
PalletStation=-10, -10, 30, 30, 0
IndexStation=-10, -10, 30, 30, 0
Hopper=-10, -10, 40, 20, 0

ASRS=0, 45, 224, 110, 0
Robot=-10, -10, 64, 80, 1
Slide=-10, -10, 190, 92, 1
Robot2=0, 0, 100,100,1
Slide2=-20, 0, 195, 100,1

[Help]
main=config.html

[PRINTER]
name=1
header=header.txt
