[IO PORT DATA]
;Interface Module Port=Port1
LSB=15
MSB=15
Index Time=4000

[SERVICE]
Machine Name=Conveyor

[FILES]
Status History=conveyor.log
Commands File=conveyor.cmd

[TIMER]
Sampling Interval=1000

[INTERLOCKS]
Conveyor Access=11
Index Enable=13

[STATIONS]
Number Of Stations=2
1=1
2=5

[DATA]
Number Of Cups=7

[MAIN WINDOW]
X=0
Y=0
W=377
H=290