[MAIN]
No Close=1

[IO PORT DATA]
Interface Module Port=PORT6

[SERVICE]
Machine Name=Conveyor

[FILES]
Status History=conveyor.log

[BUFFER SIZES]
0=3
1=3
2=3
3=3
4=3
5=3
6=3

[MAIN WINDOW]
X=8
Y=150
H=173
W=686

[COMMAND WINDOW]
X=0
Y=320

[CONTROL WINDOW]
X=0
Y=75
H=468
W=700

[TIMER]
Sampling Interval=1000
Offload Time=7000

[SAFETY BIT]
enable=0

[CONVEYOR]
; how many stations there are (starting at 1)
buffers=5
; if 'circular' is 0 then the conveyor is to be used with an ASRS
; if 'circular' is 1 then it is not. There is an inventory station.
circular=0
; which is the inventory station (starting at 0)
; inventory=3	
; the file to be used as inventory list
inventoryfile="invent.con"

[BUFFER WINDOW 0]
X=0
Y=0
W=138
H=168

[BUFFER WINDOW 1]
X=130
Y=0
W=138
H=168

[BUFFER WINDOW 2]
X=266
Y=0
W=138
H=168

[BUFFER WINDOW 3]
X=403
Y=0
W=138
H=168

[BUFFER WINDOW 4]
X=542
Y=0
W=138
H=168
