;
; This is a dummy INI file, only present so the Sequence File Editor
;  can find the Vision Command File
;
; This INI file and NOT used by the Visiion System Device Driver
;

[FILES]
Commands File = Camera.cmd
