[directories]
machine list file=C:\Documents and Settings\All Users\Application Data\Denford\machine list.ini
XNC Folder=C:\Documents and Settings\Triac\My Documents\Denford\CNC Files\
GNC Folder=C:\Documents and Settings\Triac\My Documents\Denford\CNC Files\
FNC Folder=C:\Documents and Settings\Triac\My Documents\Denford\CNC Files\
Offset Folder=C:\Documents and Settings\All Users\Application Data\Denford\

[Default Settings]
Active Machine=MICROROUTER
Metric=1
Help File=MILL.HLP
Help Reference=Help.ini
Billet X=100
Billet Y=100
Billet Z=30
Billet X Pos=65.225
Billet Y Pos=111.081
Expanded Cycles=1
Warn ON Play=1
User Level=1
;Fanuc reference (page 205)parameter 5001 #2 Cutter Compensation C can use H (=1)
Cutter Comp=0
PrimaryLanguage=1
SubLanguage=0
Machine Offset=Default Machine Offset
Simulation Offset=
ScreenUpdate=500
Reset On Rewind=TRUE
Look Ahead=4
ChecksumBeep=FALSE
ToolChangeButton=FALSE
BackGround On=TRUE
BackGround Picture=Background.bmp
MintDebug=false
Support IP=62.49.128.243
Offset Page=0
JustInstalled=TRUE

[source]
File=1
Editor=2


[RS232]
com port=0
Baud Rate=6
Data Bits=2
Parity=2
Hand Shaking=0
Stop Bits=0


[Editform]
background colour=16777215
Token G Colour=32768
Token G BackColour=16777215
Token G Style=1
Token M Colour=10485760
Token M BackColour=16777215
Token M Style=1
Token T Colour=128
Token T BackColour=16777215
Token T Style=1
Token F Colour=16711680
Token F BackColour=16777215
Token F Style=1
Token S Colour=0
Token S BackColour=16777215
Token S Style=0
Token X Colour=0
Token X BackColour=16777215
Token X Style=0
Token Y Colour=0
Token Y BackColour=16777215
Token Y Style=0
Token Z Colour=0
Token Z BackColour=16777215
Token Z Style=0
Token I Colour=0
Token I BackColour=16777215
Token I Style=0
Token J Colour=0
Token J BackColour=16777215
Token J Style=0
Token ( Colour=8388608
Token ( BackColour=16777215
Token ( Style=2
Token [ Colour=0
Token [ BackColour=16250871
Token [ Style=1
padding=SPACE
LineEnd=
NumberString=N
numberstart=10
numberInc=10
NumberSize=4
formatting=1
Font size=12
Font name=Arial
Font Style=0
FormatFile=C:\Documents and Settings\All Users\Application Data\Denford\Default.NCF

[Jog Keys]
X+=39
X-=37
Y+=38
Y-=40
Z+=33
Z-=34
IV+=190
IV-=191
Trv=101
Fup=116
Fdn=117
Sup=118
Sdn=119

[data]
Show Code=1
Expanded Cycles=0

[Button Map]
;FanucBut_O ^P
0=79,80
;FanucBut_N ^Q
1=78,81
;FanucBut_G ^R
2=71,82
;FanucBut_7 ^A
3=55,65
;FanucBut_8 ^B
4=56,66
;FanucBut_9 ^D
5=57,68
;FanucBut_X ^U
6=88,85
;FanucBut_Y ^V
7=89,86
;FanucBut_Z ^W
8=90,87
;FanucBut_4 ^[ ???
9=52,219
;FanucBut_5 ^] ???
10=53,221
;FanucBut_6 ^SPACE
11=54,32
;FanucBut_M ^I
12=77,73
;FanucBut_S ^J
13=83,74
;FanucBut_T ^K
14=84,75
;FanucBut_1 ^,
15=49,188
;FanucBut_2 ^# 
16=50,222
;FanucBut_3 ^=
17=51,187
;FanucBut_F ^L
18=70,76
;FanucBut_H ^D
19=72,68
;FanucBut_EOB ^E
20=59,69
;FanucBut_- ^+
21=189,107
;FanucBut_0 ^*
22=48,106
;FanucBut_. ^/
23=110,111
;FanucBut_POS
24=24,24
;FanucBut_PROG
25=25,25
;FanucBut_OFFSET
26=26,26
;FanucBut_SHIFT
27=$10,$10
;FanucBut_Can
28=$08,$08
;FanucBut_INPUT
29=29,29
;FanucBut_SYSTEM
30=30,30
;FanucBut_MESSAGE
31=31,31
;FanucBut_GRAPH
32=232,232
;FanucBut_ALTER
33=233,233
;FanucBut_INSERT 
34=234,234
;FanucBut_DELETE
35=$2E,$2E
;FanucButPageUp
36=$21,$21
;FanucButPageDown
37=$22,$22
;FanucButCursorLeft
38=$25,$25
;FanucButCursorRight
39=$27,$27
;FanucButCursorUp
40=$26,$26
;FanucButCursorDown
41=$28,$28
;FanucButHelp
42=42,42
;FanucButReset
43=43,43

[ControlPanel]
Top=6
Left=300
ReadOutAxesColor=0
ReadOutPanelColor=15857140


[3DGraphics]
rapid colour=255
linear colour=4227327
circular colour=8454143
plastic colour=12632256
background colour=8421376
billet material=1
move history amount=100
use plastic=0
show linears=1
show Rapids=1
show Arcs=1
show cutter=1
use Offsets=0
show move history=1
surface colour=255
grid size=0.5
Use OpenGl=1
shiny=0
matt=0
show billet=1
Texture Directory=
Custom Texture=Custom.jpg
Material Type=1

[Menu Tools]
Denford Comms_Title=0
Denford Comms_Prog=DenComm.exe
Denford Comms_Work=
Denford Comms_Param=
Denford Comms_Show=1

[Macro Variables]
500=0
501=0
502=0
503=0
504=0
505=0
506=0
507=0
508=0
509=0
510=0
511=0
512=0
513=0
514=0
515=0
516=0
517=0
518=0
519=0
520=0
521=0
522=0
523=0
524=0
525=0
526=0
527=0
528=0
529=0
530=0
531=0


[DenVR]
Plastic Colour=12632256
Texture Directory=C:\Program Files\Denford\VRMilling3\
Custom Texture=C:\Program Files\Denford\VRMilling3\Custom.jpg
Material Type=4
Billet Shape=1
Billet PolySides=6
Billet Shape File=C:\Program Files\Denford\VRMilling3\
Navigation Speed=0.28
Navigation Panel=0
AutoDatum Pos=3
AutoDatum UpperPos=1
AutoDatum ShiftX=0
AutoDatum ShiftY=0
AutoDatum ShiftZ=0
AutoDatum Shifted=0
AutoDatum=1
Show Option Buttons=1
Billet Resolution=0.4
Texture Colour=5131854
Use Texture Colour=1


[Offsets]
Work Offset File=C:\Documents and Settings\All Users\Application Data\Denford\AllOffsets.MOF
Tool Offset File=C:\Documents and Settings\All Users\Application Data\Denford\AllOffsets.MOF
Library File=C:\Documents and Settings\All Users\Application Data\Denford\AllOffsets.MOF


[Denford Compatibles]
QuickCAM Milling=MQCAM.exe_dxf_mcf
QuickCAM 3D=QuickCAM3D.exe_stl_3ds_bmp
QuickCAM PRO=QuickCAMPRO.exe_stl_3ds_bmp
QuickCAM 4D=QuickCAM4D.exe_stl_3ds
TechSoft 2d Design=2DDes32.exe_dtd

;******************************************************************
; Toolbar positions follow -> 
;******************************************************************

[Toolbar_File_Control]
Rev=2
Visible=1
DockedTo=DockBottom
DockRow=0
DockPos=729
FloatLeft=0
FloatTop=0
IconSize=2
ShowCaption=0
FloatRightX=0

[Toolbar_output]
Rev=2
Visible=1
DockedTo=DockRight
DockRow=0
DockPos=121
FloatLeft=0
FloatTop=0
IconSize=2
ShowCaption=0
FloatRightX=0

[dataInfo]
Rev=2
Visible=0
DockedTo=+
DockRow=0
DockPos=0
FloatLeft=468
FloatTop=158
IconSize=0
ShowCaption=0
FloatRightX=168

[Toolbar_Utilities]
Rev=2
Visible=1
DockedTo=DockRight
DockRow=0
DockPos=13
FloatLeft=0
FloatTop=0
IconSize=2
ShowCaption=0
FloatRightX=0

[toolbar_modal]
Rev=2
Visible=1
DockedTo=DockBottom
DockRow=0
DockPos=0
FloatLeft=0
FloatTop=0
IconSize=2
ShowCaption=0
FloatRightX=0

[Transformations]
Rev=2
Visible=0
DockedTo=+
DockRow=0
DockPos=-1
FloatLeft=197
FloatTop=299
IconSize=0
ShowCaption=0
ClientWidth=199
ClientHeight=199

[StatusToolbar]
Rev=2
Visible=1
DockedTo=DockBottom
DockRow=1
DockPos=0
FloatLeft=350
FloatTop=378
IconSize=0
ShowCaption=0
FloatRightX=0



[Materials]
Material File=C:\Documents and Settings\All Users\Application Data\Denford\VRMilling5.mat
