;Revision History:
; 27/4/00  - JHB - Put in shortest move (1 to 1.5 mm) to allow axes to decel in time
; 4/5/00   - AT  - Put basic (Auto Tool Change) section in for VR world Tool changes
; 11/05/00 - JHB - 'Post Process' section moved to the top of the file
;12/5/00   - AT - Real Machine Available=TRUE added to machine capability
;17/5/00   - AT - Shortest Distance for contouring not used-now Shortest Time (0.5 to 1 secs good)
;25/7/00   - AT - Polling delay increased to 50 for version 2.5.2 comms

[Post Process]
Library=C:\Program Files\Denford\VRMilling\LIBS\FANUCM.SLB

[Material]
Default X=100
Default Y=66
Default Z=25
Maximum X=288
Maximum Y=160
Maximum Z=200
Position X=0
Position Y=0
Position Z=0

[Home]
X=0
Y=0
Z=0
Feed=2000
Negative X=TRUE
Negative Y=TRUE
Negative Z=TRUE
Negative 4=FALSE

[Feed]
Default=100
Maximum Rate X=2000
Maximum Rate Y=2000
Maximum Rate Z=2000
Maximum Rate 4=2000
Minimum Rate=20
Steps per mill X=200
Steps per mill Y=200
Steps per mill Z=200
Steps per mill IV=200
Steps per mill F=200
Motor Direction X=1
Motor Direction Y=1
Motor Direction Z=1
Motor Direction IV=1
Max Contour Feed=600
Max Contour Angle=35
Jog Rapid Feed=1750
Shortest Contour=0
Shortest Time=0

[Spindle]
Maximum Speed=4000
Minimum Speed=250
Manual=FALSE


[Machine Capability]
Maximum Cut Depth=20
Travel X+=0
Travel Y+=0
Travel Z+=0
Travel IV+=360
Travel X-=-280
Travel Y-=-150
Travel Z-=-235
Travel IV-=0
Cutter Compensation=TRUE
High Speed Machining=TRUE
Table Size X=600
Table Size Y=230
Table Size Z=40
Under Inspection=FALSE
Feed Pot=TRUE
Speed Pot=TRUE
Real Machine Available=TRUE
Expand Arcs=FALSE
Min Chord Length=1
IV axis - A,B,C (1,2 or 3)=0

[Tool Change]
Auto Changer=TRUE
Maximum number=8
X=0
Y=0
Z=0

[Auto Tool Change]
1=M24
2=T
3=M25

[Communications]
Baud rate=57600
Com Port=1
Stop Bits=1
Mint File=TRIACNS.mnt
Polling Delay=100
M Code TimeOut=10000
Hardware Handshaking=FALSE
Control Type=7

[Input/Output Devices]
Tutor File=VRMilling.Keys
Com Port=5
Virtual World=TRITONNS.xvr
CIM RS232 Input=FALSE
Remote control cycle=FALSE
Remote control vice=FALSE

[M3]
Description=Spindle Forward
Timeout=10000
Code=3
Enabled=TRUE

[M4]
Description=Spindle Reverse
Timeout=10000
Code=4
Enabled=TRUE

[M5]
Description=Spindle Stop
Timeout=10000
Code=5
Enabled=TRUE

[M8]
Description=Coolant On
Timeout=10000
Code=8
Enabled=FALSE

[M9]
Description=Coolant Off
Timeout=10000
Code=9
Enabled=FALSE

[M10]
Description=Vice Open
Timeout=10000
Code=10
Enabled=FALSE

[M11]
Description=Vice Close
Timeout=10000
Code=11
Enabled=FALSE

[M13]
Description=Spin Fwd and Coolant on
Timeout=10000
Code=13
Enabled=FALSE

[M14]
Description=Spin Rev and Coolant on
Timeout=10000
Code=14
Enabled=FALSE

[M15]
Description=Spindle off Coolant off
Timeout=10000
Code=15
Enabled=FALSE

[M20]
Description=ATC Arm In
Timeout=10000
Code=20
Enabled=FALSE

[M21]
Description=ATC Arm Out
Timeout=10000
Code=21
Enabled=FALSE

[M22]
Description=ATC Arm Down
Timeout=10000
Code=22
Enabled=FALSE

[M23]
Description=ATC Arm Up
Timeout=10000
Code=23
Enabled=FALSE

[M24]
Description=Release Draw Bar
Timeout=10000
Code=24
Enabled=FALSE

[M25]
Description=Clamp Draw Bar
Timeout=10000
Code=25
Enabled=FALSE

[M27]
Description=Reset Carousel
Timeout=10000
Code=27
Enabled=FALSE

[M32]
Description=Carousel CW
Timeout=10000
Code=32
Enabled=FALSE

[M33]
Description=Carousel CCW
Timeout=10000
Code=33
Enabled=FALSE

[M34]
Description=Rotate Carousel Half Turn
Timeout=10000
Code=34
Enabled=FALSE

[M38]
Description=Guard open
Timeout=20000
Code=38
Enabled=FALSE

[M39]
Description=Guard Close
Timeout=10000
Code=39
Enabled=FALSE

[M62]
Description=Aux output 1 ON
Timeout=0
Code=62
Enabled=FALSE

[M64]
Description=Aux output 1 OFF
Timeout=0
Code=64
Enabled=FALSE

[M63]
Description=Aux output 2 ON
Timeout=0
Code=63
Enabled=FALSE

[M65]
Description=Aux output 2 OFF
Timeout=0
Code=65
Enabled=FALSE

[M66]
Description=Wait Aux input 1 ON
Timeout=0
Code=66
Enabled=FALSE

[M76]
Description=Wait Aux input 1 OFF
Timeout=0
Code=76
Enabled=FALSE

[M67]
Description=Wait Aux input 2 ON
Timeout=0
Code=67
Enabled=FALSE

[M77]
Description=Wait Aux input 2 OFF
Timeout=0
Code=77
Enabled=FALSE