[Help]
main=route.html
BOP=route.html

[main]
;... Use PICK and PLACE commands for the ASRS
newASRSCommands = 1

;... Use The Material Name in the Process Plan for the ASRS Inventory Location
UseMaterialName = 1