[IO PORT DATA]
Interface Module Port = PORT6

[SERVICE]
Machine Name=Conveyor

[FILES]
Status History=conveyor.log

[BUFFER SIZES]
0=4
1=4
2=4
3=4
4=4
5=10

[MAIN WINDOW]
X=13
Y=25
H=203
W=521

[COMMAND WINDOW]
X=0
Y=320

[CONTROL WINDOW]
X=0
Y=75
H=200
W=400

[TIMER]
Sampling Interval=200
Offload Time=7000

[SAFETY BIT]
enable=1
bit=6

[CONVEYOR]
; how many stations there are (starting at 1)
buffers=5
; if 'circular' is 0 then the conveyor is to be used with an ASRS
; if 'circular' is 1 then it is not. There is an inventory station.
circular=0
; which is the inventory station (starting at 0)
inventory=5	
; the file to be used as inventory list
inventoryfile="invent.con"
[BUFFER WINDOW 0]
X=0
Y=0
W=138
H=168
[BUFFER WINDOW 1]
X=0
Y=0
W=138
H=168
[BUFFER WINDOW 2]
X=0
Y=0
W=138
H=168
[BUFFER WINDOW 3]
X=0
Y=0
W=138
H=168
[BUFFER WINDOW 4]
X=0
Y=0
W=138
H=168
