[MAIN]
No Close=1

[IO PORT DATA]
Interface Module Port=PORT2B
Clamp Bit=1
Machining Cycle Bit=0
Machine Idle=1
Clamp Open=1

[SERVICE]
Machine Name=Miller

[FILES]
Status History=miller.log
Commands File=miller.cmd

[FILE EXTENSIONS]
CNC Files=TAP

[COMMS]
Port=COM4
Settings=9600,e,7,1
Flags=H1
OutBufferSize=1024
InBufferSize=512
TimeOut=20000
Send Type=3
; 1=Old Fanuc 2=PNC3 3=Denford 4=Fanuc


[TIMER]
Sampling Interval=600

[INTERLOCKS]
Part Clamp=5
Machine Access=4

[SAFETY BIT]
BIT=6
enable=0

[MAIN WINDOW]
X=12
Y=367
W=320
H=286
